---
title: "CodeBook"
output: html_document
date: "2023-04-27"
---

While the run_analysis.R script file contains detailed steps as to how the code runs, this code book hopes to provide further explanation on how the "Human Activity Recognition Using Smartphones Dataset" from Smartlab was cleaned. 

Installing packages "dplyr" and "data.table" allowed for the data to be manipulated in order to remove redunancies and to merge multiple data tables into one set.

Set your working directory to wherever the "UCI HAR Dataset" file is located on your computer. If the file is not easily found, the "file.exists" function will find the data if the WD is not already set to the proper folder where the data is located.

Assign variables to all data relevant to cleaning, to ensure that data is located within R's global environment. This is necessary for requirement #1.

1. Merges the training and the test sets to create one data set.

  rbind merges datasets together given their rows
  cbind merges datasets together given their columns

2. Extracts only the measurements on the mean and standard deviation for each measurement.

  the dim function returns the number of dimensions within an object
  
  OR
  
  read.table reads the relevant data table provided
  the grep function returns a vector
  the names function lists out names within a list

3. Uses descriptive activity names to name the activities in the data set

  as.character creates a character object
  
  extracts the labels from the activity_labels.txt file to the extractedData variable
  
  OR
  
  reads activity_labels.txt table to update values in the mergedData variable
  
  **mergedData and extractedData are similar

4. Appropriately labels the data set with descriptive variable names

  the gsub function replaces any phrase/text within a string 

5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

  the aggregate function splits extractedData into subsets according to mean
  "code" is the type of activity from activity_labels.txt
  (1 = WALKING, 2 = WALKING_UPSTAIRS, 3 = WALKING_DOWNSTAIRS, 4 = SITTING, 5 = STANDING, 6 = LAYING)
  the write.table function exports the data into a dataframe or table external to R


Reference: UCI HAR Dataset/README.txt